TRUNCATE TABLE test.assignatures;

-- ENGINYERIA INFORMATICA UPF
INSERT INTO test.assignatures VALUES
	(1, 1, 'Matemàtica Discreta', 1),
	(2, 1, 'Càlcul I', 1),
	(3, 1, 'Introducció a la Programació', 1),
	(4, 1, 'Introducció a les TIC', 1),
	(5, 1, 'Àlgebra Lineal', 1),
	(6, 1, 'Càlcul II', 1),
	(7, 1, 'Estructura de Dades i Algoritmes I', 1),
	(8, 1, 'Organització de Computadors', 1),
	(9, 1, 'Xarxes', 1),
	(10, 1, 'Mètodes Numèrics', 1),
	(11, 1, 'Estructura de Dades i Algoritmes II', 1),
	(12, 1, 'Fonaments de Física', 1),
	(13, 1, 'Probabilitat', 2),
	(14, 1, 'Programació Orientada a Objectes', 2),
	(15, 1, 'Senyals i Sistemes I', 2),
	(16, 1, 'Disseny Funcional de Programes', 2),
	(17, 1, 'Estadística', 2),
	(18, 1, 'Sistemes Operatius', 2),
	(19, 1, 'Gràfics per Ordinador', 2),
	(20, 1, 'Disseny d’Algorismes', 2),
	(21, 1, 'Aprenentatge Automàtic', 2),
	(22, 1, 'Enginyeria d’Interacció', 2),
	(23, 1, 'Introducció a la Programació Paral·lela i Distribuida', 2),
	(24, 1, 'Enginyeria de Software', 2),
	(25, 1, 'Bases de Dades', 3),
	(26, 1, 'Intel·ligència Artificial', 3),
	(27, 1, 'Teoria de la Computació', 3),
	(28, 1, 'Comunicació Tècnica en Anglès', 3),
	(29, 1, 'Sistemes Distribuits de Gran Escala', 3),
	(30, 1, 'Criptografia i Seguretat', 3),
	(31, 1, 'Compiladors', 3),
    (32, 1, 'Optatives', 3),
	(33, 1, 'Optatives', 4),
	(34, 1, 'TFG', 4);

-- ENGINYERIA EN XARXES DE TELECOMUNICAIONS UPF
INSERT INTO test.assignatures VALUES
	(35, 2, 'Matemàtica Discreta', 1),
	(36, 2, 'Càlcul I', 1),
	(37, 2, 'Introducció a la Programació', 1),
	(38, 2, 'Introducció a les TIC', 1),
	(39, 2, 'Àlgebra Lineal', 1),
	(40, 2, 'Càlcul II', 1),
	(41, 2, 'Estructura de Dades i Algoritmes I', 1),
	(42, 2, 'Organització de Computadors', 1),
	(43, 2, 'Xarxes', 1),
	(44, 2, 'Mètodes Numèrics', 1),
	(45, 2, 'Estructura de Dades i Algoritmes II', 1),
	(46, 2, 'Fonaments de Física', 1),
	(47, 2, 'Probabilitat', 2),
	(48, 2, 'Programació Orientada a Objectes', 2),
	(49, 2, 'Senyals i Sistemes I', 2),
	(50, 2, 'Medis de Transmissió i Circuits', 2),
	(51, 2, 'Estadística', 2),
	(52, 2, 'Sistemes Operatius', 2),
	(53, 2, 'Senyals i Sistemes II', 2),
	(54, 2, 'Enginyeria de Xarxes', 2),
	(55, 2, 'Aprenentatge Automàtic', 2),
	(56, 2, 'Tècniques d''Optimització', 2),
	(57, 2, 'Arquitectura de Xarxes', 2),
	(58, 2, 'Teoria de la Informació i Codificació', 2),
	(59, 2, 'Bases de Dades', 3),
	(60, 2, 'Transmissió Digital de Dades', 3),
	(61, 2, 'Simulació i Modelització de Xarxes', 3),
	(62, 2, 'Comunicació Tècnica en Anglès', 3),
	(63, 2, 'Comunicación Técnica en Inglés', 3),
	(64, 2, 'Organització d''Empreses TIC', 3),
	(65, 2, 'Criptografia i Seguretat', 3),
	(66, 2, 'Sistemes de Radiocomunicacions', 3),
	(67, 2, 'Aplicacions Telemàtiques', 3),
	(68, 2, 'Optatives', 3),
	(69, 2, 'Gestió de Projectes', 4),
	(70, 2, 'Xarxes Òptiques', 4),
	(71, 2, 'Comunicacions Mòbils', 4),
	(72, 2, 'Gestió de Xarxes i Serveis TIC', 4),
	(73, 2, 'Laboratori de Xarxes', 4),
	(74, 2, 'Optatives', 4),
	(75, 2, 'TFG', 4);
    
-- ENGINYERIA MATEMÀTICA EN CIÈNCIA DE DADES UPF
INSERT INTO test.assignatures VALUES
	(76, 3, 'Matemàtica Discreta', 1),
	(77, 3, 'Càlcul I', 1),
	(78, 3, 'Introducció a la Programació', 1),
	(79, 3, 'Introducció a les TIC', 1),
	(80, 3, 'Àlgebra Lineal', 1),
	(81, 3, 'Càlcul II', 1),
	(82, 3, 'Estructura de Dades i Algoritmes I', 1),
	(83, 3, 'Organització de Computadors', 1),
	(84, 3, 'Xarxes', 1),
	(85, 3, 'Mètodes Numèrics', 1),
	(86, 3, 'Estructura de Dades i Algoritmes II', 1),
	(87, 3, 'Fonaments de Física', 1),
	(88, 3, 'Probabilitat', 2),
	(89, 3, 'Programació Orientada a Objectes', 2),
	(90, 3, 'Senyals i Sistemes I', 2),
	(91, 3, 'Introducció a la Ciència de Xarxes', 2),
	(92, 3, 'Estadística', 2),
	(93, 3, 'Sistemes Operatius', 2),
	(94, 3, 'Gràfics per Ordinador', 2),
	(95, 3, 'Disseny d’Algorismes', 2),
	(96, 3, 'Aprenentatge Automàtic', 2),
	(97, 3, 'Tècniques d''Optimització', 2),
	(98, 3, 'Introducció a la Programació Paral·lela i Distribuida', 2),
	(99, 3, 'Arquitectura de Xarxes', 2),
	(100, 3, 'Bases de Dades', 3),
	(101, 3, 'Mineria de Dades Massives', 3),
	(102, 3, 'Models Estadístics', 3),
	(103, 3, 'Comunicació Tècnica en Anglès', 3),
	(104, 3, 'Organització d''Empreses TIC', 3),
	(105, 3, 'Criptografia i Seguretat', 3),
	(106, 3, 'Sistemes Distribuits de Gran Escala', 3),
	(107, 3, 'Models Gràfics Probablístics', 3),
	(108, 3, 'Gestió de Projectes', 4),
	(109, 3, 'Analítica Visual', 4),
	(110, 3, 'Recuperació de la Informació i Anàlisi de la Web', 4),
	(111, 3, 'Processos Estocàstics', 4),
	(112, 3, 'TFG', 4);

-- DRET UPF
INSERT INTO test.assignatures VALUES
	(113, 4, 'Introducció als Estudis i a la Ciència Jurídics', 1),
	(114, 4, 'Teoria del Dret', 1),
	(115, 4, 'Organització Constitucional de l\'Estat i Fonts del Dret', 1),
	(116, 4, 'Història del Dret', 1),
	(117, 4, 'Ciència Política', 1),
	(118, 4, 'Economia i Instruments Analítics per al\'Estudi del Dret i Fonaments del Dret Privat i de l\'Empresa', 1),
	(119, 4, 'Drets i Llibertats Fonamentals/ FundamentalRights and Freedoms', 1),
	(120, 4, 'Dret Internacional Públic', 2),
	(121, 4, 'Contractes', 2),
	(122, 4, 'Dret Penal: Part General', 2),
	(123, 4, 'Dret de la Unió Europea', 2),
	(124, 4, 'Institucions Bàsiques del Dret Administratiu', 2),
	(125, 4, 'Propietats i Drets Reals / Property', 2),
	(126, 4, 'Activitat de les Administracions', 2),
	(127, 4, 'Dret Financer', 2),
	(128, 4, 'Dret Penal: Part Especial', 2),
	(129, 4, 'Dret Mercantil: Dret de Societats', 3),
	(130, 4, 'Dret de Danys / Law of Damages', 3),
	(131, 4, 'Urbanisme i Dret del Territori', 3),
	(132, 4, 'Dret Mercantil: Dret de la Competència i Propietat Intel·lectual i Industrial / BusinessLaw. Antitrust and Industrial and IntellectualProperty Law', 3),
	(133, 4, 'Dret Col·lectiu del Treball', 3),
	(134, 4, 'Dret Tributari', 3),
	(135, 4, 'Dret Individual del Treball i Protecció Social', 3),
	(136, 4, 'Introduction to Common Law', 3),
	(137, 4, 'Dret de Família', 3),
	(138, 4, 'Dret Processal Civil', 4),
	(139, 4, 'Dret de Successions', 4),
	(140, 4, 'Dret Processal Civil Internacional', 4),
	(141, 4, 'Conflicte de Lleis', 4),
	(142, 4, 'Dret Processal Penal', 4),
	(143, 4, 'Dret Mercantil: Dret Concursal', 4),
	(144, 4, 'Filosofia del Dret / Philosophy of Law', 4),
	(145, 4, 'Resolució Alternativa de Conflictes /Alternative Dispute Resolution', 4),
	(146, 4, 'TFG', 4);
    
-- RELACIONS LABORALS UPF
INSERT INTO test.assignatures VALUES 
    (147, 6, 'Història Social i Jurídica Contemporània', 1),
    (148, 6, 'Introducció a l''Economia', 1),
    (149, 6, 'Dret Constitucional i Europeu', 1),
    (150, 6, 'Dret del Treball I', 1),
    (151, 6, 'Introducció al Dret Privat i de l''Empresa II', 1),
    (152, 6, 'Introducció al Dret', 1),
    (153, 6, 'TIC per a les Ciències Socials', 1),
    (154, 6, 'Introducció al Dret Privat i de l''Empresa I', 1),
    (155, 6, 'Introducció a la Psicologia', 1),
    (156, 6, 'Dret Penal Socioeconòmic', 1),
    (157, 6, 'Dret del Treball II', 1),
    (158, 6, 'Psicologia del Treball', 1),
    (159, 6, 'Comptabilitat', 2),
    (160, 6, 'Sociologia del Treball', 2),
    (161, 6, 'Organització i Mètodes de Treball I', 2),
    (162, 6, 'Direcció de Persones II', 2),
    (163, 6, 'Mètodes Quantitatius d''Investigació Social', 2),
    (164, 6, 'Direcció de Persones I', 2),
    (165, 6, 'Dret Sindical I', 2),
    (166, 6, 'Dret Sindical II', 2),
    (167, 6, 'Institucions Bàsiques de Dret Administratiu', 2),
    (168, 6, 'Organització i Mètodes de Treball II', 2),
    (169, 6, 'Dret de la Seguretat Social I', 2),
    (170, 6, 'Prevenció de Riscos Laborals', 2),
    (171, 6, 'Dret Processal Laboral I', 3),
    (172, 6, 'Dret de la Protecció Social', 3),
    (173, 6, 'Salut Laboral I', 3),
    (174, 6, 'Dret Processal Laboral II', 3),
    (175, 6, 'Dret de la Seguretat Social II', 3),
    (176, 6, 'Salut Laboral II', 3),
    (177, 6, 'Dret Tributari', 3),
    (178, 6, 'Tributació Empresarial', 3),
    (179, 6, 'Règims Especials de la Seguretat Social', 3),
    (180, 6, 'Optatives', 3),
    (181, 6, 'Economia Laboral', 4),
    (182, 6, 'Nacionalitat i Estrangeria', 4),
    (182, 6, 'Processos de Negociació Col·lectiva', 4),
    (182, 6, 'Optatives', 4),
    (182, 6, 'TFG', 4);
    






